server:
  port: 8686

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: iam-service
          uri: lb://security-demo
          predicates:
            - Path=/iam/**
        - id: storage-service
          uri: lb://storage
          predicates:
            - Path=/storage/**
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  swagger-ui:
    enabled: true
springdoc:
  api-docs:
    enabled: true
    group: gateway-api
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: API Gateway Service
        url: /v3/api-docs/gateway-api
      - name: IAM Service
        url: /iam/v3/api-docs
      - name: Storage Service
        url: /storage/v3/api-docs