server:
  port: 8099
spring:
  application:
    name: storage
  datasource:
    url: jdbc:postgresql://localhost:5432/StorageDB
    username: postgres
    password: postdb
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
  storage:
    client-id: abc
    client-secret: cba
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format-sql: true
      show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #      issuer-uri: http://localhost:8080/realms/IAM
          #      jwk-set-uri: http://localhost:8080/realms/IAM/protocol/openid-connect/certs
          jwk-set-uris:
            sso: http://localhost:8080/realms/IAM/protocol/openid-connect/certs
            internal: http://localhost:8090/api/users/certificate/.well-known/jwks.json
jwt:
  jwk-set-uris:
    sso: http://localhost:8080/realms/IAM/protocol/openid-connect/certs
    internal: http://localhost:8090/api/users/certificate/.well-known/jwks.json
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    version: openapi_3_0
file:
  upload-dir: uploadFile
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true